/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Toolkit;

public class DueList extends javax.swing.JFrame {
        String url = "jdbc:mysql://localhost:3306/lms_db";
        String user = "root";
        String pass = "VRINDA";
        // Connection con = DriverManager.getConnection(url, username, password);
        Connection con;
        PreparedStatement pst;
        ResultSet rt;
        int id = 0;

        /**
         * Creates new form DueList
         */
        public void showDetails() {
                try {
                        con = DriverManager.getConnection(url, user, pass);
                        pst = con.prepareStatement(
                                        "SELECT *,DATEDIFF(CURRENT_DATE,issue_books.due_date) as dateDiff FROM issue_books JOIN books ON books.book_id=issue_books.book_id JOIN students ON students.student_id=issue_books.student_id WHERE issue_books.due_date < CURRENT_DATE");
                        rt = pst.executeQuery();
                        DefaultTableModel tabModel = (DefaultTableModel) (dueListDetailsTab.getModel());
                        tabModel.setRowCount(0);
                        while (rt.next()) {
                                Vector issuedRow = new Vector();
                                issuedRow.add(rt.getInt("issue_id"));
                                issuedRow.add(rt.getString("book_id"));
                                issuedRow.add(rt.getString("title"));
                                issuedRow.add(rt.getString("student_id"));
                                issuedRow.add(rt.getString("name"));
                                issuedRow.add(rt.getString("issue_date"));
                                issuedRow.add(rt.getString("due_date"));
                                issuedRow.add(rt.getString("status"));
                                issuedRow.add("₹" + rt.getInt("dateDiff") * 10);
                                tabModel.addRow(issuedRow);
                        }
                } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                }
        }

        public DueList() {
                initComponents();
                setSize(Toolkit.getDefaultToolkit().getScreenSize()); // ✅ Ensure full screen
                setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // ✅ Maximize on startup
                setVisible(true);
                showDetails(); // ✅ Keep this to load data into the table
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                dueListDetailsTab = new javax.swing.JTable();
                jButton5 = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100),
                                new java.awt.Dimension(32767, 100));
                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                // Set the background of the entire JFrame to white
                getContentPane().setBackground(new java.awt.Color(255, 255, 255));
                // Set other properties of the JFrame
                setBackground(new java.awt.Color(255, 255, 255));
                setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Ensure full-screen mode
                setUndecorated(true);
                // Set the background of jPanel1 and jPanel3 to white
                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel3.setBackground(new java.awt.Color(255, 255, 255));
                jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(75, 156, 211));
                jLabel1.setText("Due Details");
                jLabel2.setIcon(
                                new javax.swing.ImageIcon(getClass()
                                                .getResource("/icons/duelist.png"))); // NOI18N
                dueListDetailsTab.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                },
                                new String[] {
                                                "ID", "Book ID", "Book Title", "Student ID", "Student Name",
                                                "Issue Date", "Due Date", "Status",
                                                "Due Fine"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class,
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class,
                                        java.lang.String.class
                        };
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, false, false, false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                dueListDetailsTab.setToolTipText(
                                "Fine for every due date is ₹10. Please fill fine while returning the book.");
                dueListDetailsTab.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
                dueListDetailsTab.setForeground(new java.awt.Color(0, 0, 0));
                dueListDetailsTab.setShowVerticalLines(true);
                dueListDetailsTab.setShowHorizontalLines(true);
                dueListDetailsTab.setBorder(new javax.swing.border.EtchedBorder());
                int width = (int) (Toolkit.getDefaultToolkit().getScreenSize().width);
                int height = (int) (Toolkit.getDefaultToolkit().getScreenSize().height);
                int widthMin = (int) (width * 0.03);
                int widthMid = (int) (width * 0.04);
                int widthMidMax = (int) (width * 0.06);
                int widthStr = (int) (width * 0.12);
                int tableWidth = 0;
                jScrollPane1.setViewportView(dueListDetailsTab);
                if (dueListDetailsTab.getColumnModel().getColumnCount() > 0) {
                        dueListDetailsTab.getColumnModel().getColumn(0).setMinWidth(widthMin);
                        dueListDetailsTab.getColumnModel().getColumn(0).setPreferredWidth(widthMin);
                        dueListDetailsTab.getColumnModel().getColumn(0).setMaxWidth(widthMin);
                        tableWidth += widthMin;
                        dueListDetailsTab.getColumnModel().getColumn(1).setMinWidth(widthMid);
                        dueListDetailsTab.getColumnModel().getColumn(1).setPreferredWidth(widthMid);
                        dueListDetailsTab.getColumnModel().getColumn(1).setMaxWidth(widthMid);
                        tableWidth += widthMid;
                        dueListDetailsTab.getColumnModel().getColumn(2).setMinWidth(widthStr);
                        dueListDetailsTab.getColumnModel().getColumn(2).setPreferredWidth(widthStr);
                        dueListDetailsTab.getColumnModel().getColumn(2).setMaxWidth(widthStr);
                        tableWidth += widthStr;
                        dueListDetailsTab.getColumnModel().getColumn(3).setMinWidth(widthMid);
                        dueListDetailsTab.getColumnModel().getColumn(3).setPreferredWidth(widthMid);
                        dueListDetailsTab.getColumnModel().getColumn(3).setMaxWidth(widthMid);
                        tableWidth += widthMid;
                        dueListDetailsTab.getColumnModel().getColumn(4).setMinWidth(widthStr);
                        dueListDetailsTab.getColumnModel().getColumn(4).setPreferredWidth(widthStr);
                        dueListDetailsTab.getColumnModel().getColumn(4).setMaxWidth(widthStr);
                        tableWidth += widthStr;
                        dueListDetailsTab.getColumnModel().getColumn(5).setMinWidth(widthMidMax);
                        dueListDetailsTab.getColumnModel().getColumn(5).setPreferredWidth(widthMidMax);
                        dueListDetailsTab.getColumnModel().getColumn(5).setMaxWidth(widthMidMax);
                        tableWidth += widthMidMax;
                        dueListDetailsTab.getColumnModel().getColumn(6).setMinWidth(widthMidMax);
                        dueListDetailsTab.getColumnModel().getColumn(6).setPreferredWidth(widthMidMax);
                        dueListDetailsTab.getColumnModel().getColumn(6).setMaxWidth(widthMidMax);
                        tableWidth += widthMidMax;
                        dueListDetailsTab.getColumnModel().getColumn(7).setMinWidth(widthMidMax);
                        dueListDetailsTab.getColumnModel().getColumn(7).setPreferredWidth(widthMidMax);
                        dueListDetailsTab.getColumnModel().getColumn(7).setMaxWidth(widthMidMax);
                        tableWidth += widthMidMax;
                        dueListDetailsTab.getColumnModel().getColumn(8).setMinWidth(widthMidMax);
                        dueListDetailsTab.getColumnModel().getColumn(8).setPreferredWidth(widthMidMax);
                        dueListDetailsTab.getColumnModel().getColumn(8).setMaxWidth(widthMidMax);
                        tableWidth += widthMidMax;
                }
                jButton5.setBackground(new java.awt.Color(75, 156, 211));
                jButton5.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/addNewBooksIcons/icons8_Rewind_48px.png"))); // NOI18N
                jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jButton5MouseClicked(evt);
                        }
                });
                jPanel3.setBackground(new java.awt.Color(75, 156, 211));
                jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jPanel3MouseClicked(evt);
                        }
                });
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-close-30.png"))); // NOI18N
                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel3Layout.createSequentialGroup()
                                                                                .addContainerGap(5, 5)
                                                                                .addComponent(jLabel3)
                                                                                .addGap(12, 12, 12)));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                42, Short.MAX_VALUE)));
                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                int widthAdjust = (int) (width - tableWidth) / 2;
                int widthAdjust2 = (int) (width * 0.40);
                int heightAdjust = (int) (height * 0.1);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap(widthAdjust, widthAdjust)
                                                                .addComponent(jScrollPane1, tableWidth, tableWidth,
                                                                                tableWidth)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(filler1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(widthAdjust, widthAdjust))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jButton5)
                                                                .addGap(widthAdjust2, widthAdjust2, widthAdjust2)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                606,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jButton5)
                                                                                .addComponent(jPanel3, 55, 55, 55))
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGap(heightAdjust + 55,
                                                                                                heightAdjust + 55,
                                                                                                heightAdjust + 55)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel1))
                                                                .addGap(heightAdjust, heightAdjust, heightAdjust)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(filler1,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(10, 10, 10)));
                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton5MouseClicked
                this.dispose();
                new Dashboard().setVisible(true);
        }// GEN-LAST:event_jButton5MouseClicked

        private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel3MouseClicked
                this.dispose();
        }// GEN-LAST:event_jPanel3MouseClicked

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(DueList.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(DueList.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(DueList.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(DueList.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new DueList().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTable dueListDetailsTab;
        private javax.swing.Box.Filler filler1;
        private javax.swing.JButton jButton5;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration//GEN-END:variables
}
