/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageStudents extends javax.swing.JFrame {
    String url = "jdbc:mysql://localhost:3306/lms_db";
    String user = "root";
    String pass = "VRINDA";
    // Connection con = DriverManager.getConnection(url, username, email);
    Connection con;
    PreparedStatement pst;
    ResultSet rt;
    int id, selectedRow = 0;

    public void clearData() {
        name.setText("");
        phone.setText("");
        username.setText("");
        email.setText("");
        course.setSelectedIndex(0);
        address.setText("");
        confirmationCheck.setSelected(false);
        if (id > 0) {
            id = 0;
            editStudent.setEnabled(false);
            deleteStudent.setEnabled(false);
        }
    }

    public void showStudents() {
        try {
            con = DriverManager.getConnection(url, user, pass);
            pst = con.prepareStatement("SELECT * FROM students");
            rt = pst.executeQuery();
            DefaultTableModel tabModel = (DefaultTableModel) (student_table.getModel());
            tabModel.setRowCount(0);
            while (rt.next()) {
                Vector studentRow = new Vector();
                studentRow.add(rt.getInt("student_id"));
                studentRow.add(rt.getString("name"));
                studentRow.add(rt.getString("username"));
                studentRow.add(rt.getString("phone"));
                studentRow.add(rt.getString("course"));
                studentRow.add(rt.getString("address"));
                tabModel.addRow(studentRow);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Some error occured.");
        }
    }

    /**
     * Creates new form ManageStudents
     */
    public ManageStudents() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Maximize the JFrame
        showStudents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        addStudent = new javax.swing.JButton();
        editStudent = new javax.swing.JButton();
        deleteStudent = new javax.swing.JButton();
        clearStudent = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        confirmationCheck = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        student_table = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        jPanel1.setBackground(new java.awt.Color(75, 156, 211));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Name");
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone");
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course");
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "BSc", "BTech", "BA" }));
        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);
        addStudent.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        addStudent.setForeground(new java.awt.Color(51, 51, 51));
        addStudent.setText("ADD NEW STUDENT");
        addStudent.setEnabled(false);
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });
        editStudent.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        editStudent.setText("EDIT EXISTING STUDENT");
        editStudent.setEnabled(false);
        editStudent.setMaximumSize(new java.awt.Dimension(191, 28));
        editStudent.setMinimumSize(new java.awt.Dimension(191, 28));
        editStudent.setPreferredSize(new java.awt.Dimension(191, 28));
        editStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentActionPerformed(evt);
            }
        });
        deleteStudent.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        deleteStudent.setText("DELETE STUDENT");
        deleteStudent.setEnabled(false);
        deleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentActionPerformed(evt);
            }
        });
        clearStudent.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        clearStudent.setText("CLEAR FORM");
        clearStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearStudentMouseClicked(evt);
            }
        });
        jButton5.setBackground(new java.awt.Color(75, 156, 211));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addNewBooksIcons/icons8_Rewind_48px.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");
        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        confirmationCheck.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        confirmationCheck.setForeground(new java.awt.Color(255, 255, 255));
        confirmationCheck.setText("Student has paid Rs. 100 registration fee.");
        confirmationCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmationCheckMouseClicked(evt);
            }
        });
        confirmationCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmationCheckActionPerformed(evt);
            }
        });
        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD STUDENT");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        int width = (int) (Toolkit.getDefaultToolkit().getScreenSize().width);
        int height = (int) (Toolkit.getDefaultToolkit().getScreenSize().height);
        int panel1gap = (int) (width * 0.075);
        int topGap = (int) (height * 0.1);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(panel1gap, panel1gap, panel1gap)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(deleteStudent, 250, 250, 250)
                                                .addGap(20, 20, 20)
                                                .addComponent(clearStudent, 250, 250, 250))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(addStudent, 250, 250, 250)
                                                .addGap(20, 20, 20)
                                                .addComponent(editStudent, 250, 250, 250))
                                        .addComponent(confirmationCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 405,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(name, 520, 520, 520)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel1)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout
                                                        .createSequentialGroup()
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(username, 250, 250, 250)
                                                                        .addGap(20, 20, 20))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(phone, 250, 250, 250))
                                                                        .addGap(20, 20, 20)))
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(course, 250, 250, 250)
                                                                .addComponent(jLabel8)
                                                                .addComponent(email, 250, 250, 250)
                                                                .addComponent(jLabel3))))
                                        .addComponent(jLabel4)
                                        .addComponent(jScrollPane1, 520, 520, 520))));
        int labelGap = (int) (height * 0.03);
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(topGap, topGap, topGap)
                                .addComponent(jLabel9)
                                .addGap(labelGap, labelGap, labelGap)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(labelGap, labelGap, labelGap)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                        .addComponent(username))
                                .addGap(labelGap, labelGap, labelGap)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(labelGap, labelGap, labelGap)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(labelGap, labelGap, labelGap)
                                .addComponent(confirmationCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editStudent, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(clearStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(labelGap, labelGap, labelGap)));
        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 156, 211));
        jLabel5.setText("Manage Students");
        jLabel6.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/icons/student.png"))); // NOI18N
        student_table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null },
                        { null, null, null, null, null, null }
                },
                new String[] {
                        "ID", "Name", "Username", "Phone", "Course", "Address"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        student_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                student_tableMouseClicked(evt);
            }
        });
        student_table.setForeground(new java.awt.Color(0, 0, 0));
        student_table.setShowVerticalLines(true);
        student_table.setShowHorizontalLines(true);
        student_table.setBorder(new javax.swing.border.EtchedBorder());
        int widthMin = (int) (width * 0.03);
        int widthMid = (int) (width * 0.04);
        int widthMidMax = (int) (width * 0.06);
        int widthStr = (int) (width * 0.12);
        int table = 0;
        jScrollPane2.setViewportView(student_table);
        if (student_table.getColumnModel().getColumnCount() > 0) {
            student_table.getColumnModel().getColumn(0).setMinWidth(widthMin);
            student_table.getColumnModel().getColumn(0).setPreferredWidth(widthMin);
            student_table.getColumnModel().getColumn(0).setMaxWidth(widthMin);
            table += widthMin;
            student_table.getColumnModel().getColumn(1).setMinWidth(widthStr);
            student_table.getColumnModel().getColumn(1).setPreferredWidth(widthStr);
            student_table.getColumnModel().getColumn(1).setMaxWidth(widthStr);
            table += widthStr;
            student_table.getColumnModel().getColumn(2).setMinWidth(widthMid);
            student_table.getColumnModel().getColumn(2).setPreferredWidth(widthMid);
            student_table.getColumnModel().getColumn(2).setMaxWidth(widthMid);
            table += widthMid;
            student_table.getColumnModel().getColumn(3).setMinWidth(widthStr);
            student_table.getColumnModel().getColumn(3).setPreferredWidth(widthStr);
            student_table.getColumnModel().getColumn(3).setMaxWidth(widthStr);
            table += widthStr;
            student_table.getColumnModel().getColumn(4).setMinWidth(widthMid);
            student_table.getColumnModel().getColumn(4).setPreferredWidth(widthMid);
            student_table.getColumnModel().getColumn(4).setMaxWidth(widthMid);
            table += widthMid;
            student_table.getColumnModel().getColumn(5).setMinWidth(widthStr);
            student_table.getColumnModel().getColumn(5).setPreferredWidth(widthStr);
            student_table.getColumnModel().getColumn(5).setMaxWidth(widthStr);
            table += widthStr;
        }
        jPanel10.setBackground(new java.awt.Color(75, 156, 211));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-close-30.png"))); // NOI18N
        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addContainerGap(14, Short.MAX_VALUE)
                                .addComponent(jLabel25)
                                .addGap(12, 12, 12)));
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addContainerGap()));
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        int jlabel5Gap = (int) (topGap + topGap * 0.5);
        int jTableGap = (int) (height * 0.05);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, table, table, table)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)))
                                .addContainerGap(37, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(topGap, topGap, topGap)
                                                .addComponent(jLabel6))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(jlabel5Gap, jlabel5Gap, jlabel5Gap)
                                                .addComponent(jLabel5))
                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(jTableGap, jTableGap, jTableGap)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(60, Short.MAX_VALUE)));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        int layoutAdjust1 = (int) (width * 0.4);
        int layoutAdjust2 = (int) (width * 0.6);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, layoutAdjust1,
                                        layoutAdjust1, layoutAdjust1)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel2, layoutAdjust2, layoutAdjust2, layoutAdjust2)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
    }// GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton5MouseClicked
        this.dispose();
        new Dashboard().setVisible(true);
    }// GEN-LAST:event_jButton5MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel10MouseClicked
        this.dispose();
    }// GEN-LAST:event_jPanel10MouseClicked

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addStudentActionPerformed
        if (name.getText().isEmpty() || phone.getText().isEmpty() || username.getText().isEmpty()
                || email.getText().isEmpty() || course.getSelectedItem().toString().isEmpty()
                || address.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fill all the data before submission.");
        } else {
            try {
                con = DriverManager.getConnection(url, user, pass);
                pst = con.prepareStatement(
                        "INSERT INTO students (name,username, email, phone, course, address) VALUES (?,?,?,?,?,?)");
                pst.setString(1, name.getText());
                pst.setString(2, username.getText());
                pst.setString(3, email.getText());
                pst.setString(4, phone.getText());
                pst.setString(5, course.getSelectedItem().toString());
                pst.setString(6, address.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student has been successfully added.");
                showStudents();
                clearData();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }// GEN-LAST:event_addStudentActionPerformed

    private void clearStudentMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_clearStudentMouseClicked
        clearData();
    }// GEN-LAST:event_clearStudentMouseClicked

    private void student_tableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_student_tableMouseClicked
        selectedRow = student_table.getSelectedRow();
        if (student_table.getSelectedRowCount() > 0) {
            addStudent.setEnabled(false);
            deleteStudent.setEnabled(true);
            editStudent.setEnabled(true);
            id = (int) student_table.getValueAt(selectedRow, 0);
            String sqlusername, useremail;
            try {
                con = DriverManager.getConnection(url, user, pass);
                pst = con.prepareStatement("SELECT username,email FROM students WHERE student_id=?");
                pst.setInt(1, id);
                rt = pst.executeQuery();
                rt.next();
                sqlusername = rt.getString("username");
                useremail = rt.getString("email");
                username.setText(sqlusername);
                email.setText(useremail);
                name.setText(student_table.getValueAt(selectedRow, 1).toString());
                phone.setText(student_table.getValueAt(selectedRow, 3).toString());
                course.setSelectedItem(student_table.getValueAt(selectedRow, 4).toString());
                address.setText(student_table.getValueAt(selectedRow, 5).toString());
                confirmationCheck.setSelected(true);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Some error occured.");
            }
        } else {
            clearData();
        }
    }// GEN-LAST:event_student_tableMouseClicked

    private void confirmationCheckActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmationCheckActionPerformed
    }// GEN-LAST:event_confirmationCheckActionPerformed

    private void confirmationCheckMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_confirmationCheckMouseClicked
        if (confirmationCheck.isSelected()) {
            if (id == 0) {
                addStudent.setEnabled(true);
            }
        } else {
            addStudent.setEnabled(false);
        }
    }// GEN-LAST:event_confirmationCheckMouseClicked

    private void editStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editStudentActionPerformed
        if (id != 0) {
            if (name.getText().isEmpty() || username.getText().isEmpty() || phone.getText().isEmpty()
                    || course.getSelectedItem().toString().isEmpty() || address.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Fill all the data before submission.");
            } else {
                try {
                    con = DriverManager.getConnection(url, user, pass);
                    if (email.getText().isEmpty()) {
                        pst = con.prepareStatement(
                                "UPDATE students SET name=?,username=?,phone=?,course=?,address=? WHERE student_id=?");
                        pst.setString(1, name.getText());
                        pst.setString(2, username.getText());
                        pst.setString(3, phone.getText());
                        pst.setString(4, course.getSelectedItem().toString());
                        pst.setString(5, address.getText());
                        pst.setInt(6, id);
                    } else {
                        pst = con.prepareStatement(
                                "UPDATE students SET name=?,username=?,email=?,phone=?,course=?,address=? WHERE student_id=?");
                        pst.setString(1, name.getText());
                        pst.setString(2, username.getText());
                        pst.setString(3, email.getText());
                        pst.setString(4, phone.getText());
                        pst.setString(5, course.getSelectedItem().toString());
                        pst.setString(6, address.getText());
                        pst.setInt(7, id);
                    }
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Student's details has been successfully updated.");
                    showStudents();
                    clearData();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Some error occured. Please try again.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a row to edit.");
        }
    }// GEN-LAST:event_editStudentActionPerformed

    private void deleteStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteStudentActionPerformed
        if (id != 0) {
            try {
                con = DriverManager.getConnection(url, user, pass);
                pst = con.prepareStatement("DELETE FROM students WHERE student_id=?");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student has been successfully deleted.");
                showStudents();
                clearData();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Some error occured. Please try again.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a row to delete.");
        }
    }// GEN-LAST:event_deleteStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudent;
    private javax.swing.JTextArea address;
    private javax.swing.JButton clearStudent;
    private javax.swing.JCheckBox confirmationCheck;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JButton deleteStudent;
    private javax.swing.JButton editStudent;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTable student_table;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
