/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

public class ReturnBook extends javax.swing.JFrame {
        String url = "jdbc:mysql://localhost:3306/lms_db";
        String user = "root";
        String pass = "VRINDA";
        // Connection con = DriverManager.getConnection(url, username, password);
        Connection con;
        PreparedStatement pst;
        ResultSet rt;
        int book_id_var, student_id_var = 0;

        /**
         * Creates new form ReturnBook
         */
        public void clearData() {
                book_id.setText("");
                student_id.setText("");
                bookId.setText("");
                studentId.setText("");
                bookTitle.setText("");
                bookAuthor.setText("");
                bookLanguage.setText("");
                bookISBN.setText("");
                bookPublisher.setText("");
                studentName.setText("");
                studentCourse.setText("");
                studentPhone.setText("");
                studentAddress.setText("");
                book_id_var = 0;
                student_id_var = 0;
        }

        public ReturnBook() {
                initComponents();
                this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Maximize the JFrame
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jButton5 = new javax.swing.JButton();
                bookId = new javax.swing.JLabel();
                bookTitle = new javax.swing.JLabel();
                bookAuthor = new javax.swing.JLabel();
                bookISBN = new javax.swing.JLabel();
                bookLanguage = new javax.swing.JLabel();
                bookPublisher = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                studentId = new javax.swing.JLabel();
                studentName = new javax.swing.JLabel();
                studentPhone = new javax.swing.JLabel();
                studentCourse = new javax.swing.JLabel();
                studentAddress = new javax.swing.JLabel();
                jPanel5 = new javax.swing.JPanel();
                jLabel16 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                book_id = new javax.swing.JTextField();
                jLabel19 = new javax.swing.JLabel();
                student_id = new javax.swing.JTextField();
                returnBook = new javax.swing.JButton();
                findBook = new javax.swing.JButton();
                jPanel10 = new javax.swing.JPanel();
                jLabel25 = new javax.swing.JLabel();
                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(255, 255, 255));
                setUndecorated(true);
                jPanel1.setBackground(new java.awt.Color(75, 156, 211));
                jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Book Details");
                jLabel2.setIcon(
                                new javax.swing.ImageIcon(getClass()
                                                .getResource("/addNewBooksIcons/icons8_Literature_100px_1.png"))); // NOI18N
                jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Book ID      :");
                jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Book Title  :");
                jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Author        :");
                jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("ISBN           :");
                jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 255, 255));
                jLabel7.setText("Language   :");
                jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(255, 255, 255));
                jLabel8.setText("Publisher   :");
                jButton5.setBackground(new java.awt.Color(75, 156, 211));
                jButton5.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/addNewBooksIcons/icons8_Rewind_48px.png"))); // NOI18N
                jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jButton5MouseClicked(evt);
                        }
                });
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });
                bookId.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                bookId.setForeground(new java.awt.Color(255, 255, 255));
                bookTitle.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                bookTitle.setForeground(new java.awt.Color(255, 255, 255));
                bookAuthor.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                bookAuthor.setForeground(new java.awt.Color(255, 255, 255));
                bookISBN.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                bookISBN.setForeground(new java.awt.Color(255, 255, 255));
                bookLanguage.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                bookLanguage.setForeground(new java.awt.Color(255, 255, 255));
                bookPublisher.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                bookPublisher.setForeground(new java.awt.Color(255, 255, 255));
                jPanel3.setBackground(new java.awt.Color(75, 156, 211));
                jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(255, 255, 255));
                jLabel9.setText("Student Details");
                jLabel10.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/addNewBooksIcons/icons8_Student_Registration_100px_2.png"))); // NOI18N
                jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel11.setForeground(new java.awt.Color(255, 255, 255));
                jLabel11.setText("Student ID        :");
                jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(255, 255, 255));
                jLabel12.setText("Student Name  :");
                jLabel13.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel13.setForeground(new java.awt.Color(255, 255, 255));
                jLabel13.setText("Student Phone :");
                jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel14.setForeground(new java.awt.Color(255, 255, 255));
                jLabel14.setText("Course             :");
                jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel15.setForeground(new java.awt.Color(255, 255, 255));
                jLabel15.setText("Address           :");
                studentId.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                studentId.setForeground(new java.awt.Color(255, 255, 255));
                studentName.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                studentName.setForeground(new java.awt.Color(255, 255, 255));
                studentPhone.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                studentPhone.setForeground(new java.awt.Color(255, 255, 255));
                studentCourse.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                studentCourse.setForeground(new java.awt.Color(255, 255, 255));
                studentAddress.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                studentAddress.setForeground(new java.awt.Color(255, 255, 255));
                int width = (int) (Toolkit.getDefaultToolkit().getScreenSize().width);
                int height = (int) (Toolkit.getDefaultToolkit().getScreenSize().height);
                int constantGap = (int) (width * 0.1);
                int panel1width = (int) (width * 0.33);
                int panel2width = (int) (width * 0.33);
                int panel3width = (int) (width - (panel1width + panel2width));
                int topGap = (int) (height * 0.05);
                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(80, 80, 80) // Adjust starting gap if needed
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel11) // Student
                                                                                                                                        // ID
                                                                                                                .addComponent(jLabel12) // Student
                                                                                                                                        // Name
                                                                                                                .addComponent(jLabel13) // Student
                                                                                                                                        // Phone
                                                                                                                .addComponent(jLabel14) // Course
                                                                                                                .addComponent(jLabel15)) // Address
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel3Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(studentId,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                276,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(studentName)
                                                                                                                .addComponent(studentPhone)
                                                                                                                .addComponent(studentCourse)
                                                                                                                .addComponent(studentAddress)))
                                                                                .addGroup(jPanel3Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel10) // Any
                                                                                                                        // additional
                                                                                                                        // label
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel9))) // Another
                                                                                                                         // label
                                                                                                                         // or
                                                                                                                         // value
                                                                .addContainerGap(30, Short.MAX_VALUE)));
                // int
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(topGap + 60, topGap + 60, topGap + 60)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel10)
                                                                                .addComponent(jLabel9))
                                                                .addGap(40, 40, 40)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel11)
                                                                                .addComponent(studentId))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel12)
                                                                                .addComponent(studentName))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel13)
                                                                                .addComponent(studentPhone))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel14)
                                                                                .addComponent(studentCourse))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel15)
                                                                                .addComponent(studentAddress))
                                                                .addContainerGap(52, Short.MAX_VALUE)));
                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                // Horizontal Group
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                // Back button at top
                                                                                .addComponent(jButton5)
                                                                                // Main form content
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(constantGap,
                                                                                                                constantGap,
                                                                                                                constantGap) // Additional
                                                                                                // indent
                                                                                                // for
                                                                                                // form
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                // Header
                                                                                                                // with
                                                                                                                // jLabel1
                                                                                                                // and
                                                                                                                // jLabel2
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel2)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                181,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                // Form
                                                                                                                // fields
                                                                                                                // and
                                                                                                                // labels
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                .addComponent(jLabel6)
                                                                                                                                                .addComponent(jLabel7)
                                                                                                                                                .addComponent(jLabel8))
                                                                                                                                .addGap(20,
                                                                                                                                                20,
                                                                                                                                                20)
                                                                                                                                // //
                                                                                                                                // Gap
                                                                                                                                // between
                                                                                                                                // labels
                                                                                                                                // and
                                                                                                                                // fields
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                // Fields
                                                                                                                                                // column
                                                                                                                                                .addComponent(bookId,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                200,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(bookTitle,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                200,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(bookAuthor,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                200,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(bookISBN,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                200,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(bookLanguage,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                200,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(bookPublisher,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                200,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)));
                // Vertical Group
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jButton5) // Back button at top
                                                                .addGap(topGap, topGap, topGap)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel1))
                                                                .addGap(40, 40, 40)
                                                                // Form fields
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(bookId,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(bookTitle,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(bookAuthor,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(bookISBN,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(bookLanguage,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel8)
                                                                                .addComponent(bookPublisher,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(49, Short.MAX_VALUE)));
                jLabel3.getAccessibleContext().setAccessibleName("Book ID          :");
                jLabel3.getAccessibleContext().setAccessibleDescription("");
                jPanel5.setBackground(new java.awt.Color(255, 255, 255));
                jPanel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
                jLabel16.setFont(new java.awt.Font("Liberation Sans", 1, 32)); // NOI18N
                jLabel16.setForeground(new java.awt.Color(75, 156, 211));
                jLabel16.setText("Return Book");
                jLabel17.setSize(100, 100);
                jLabel17.setIcon(
                                new javax.swing.ImageIcon(
                                                getClass().getResource("/icons/books.png"))); // NOI18N
                jLabel18.setBackground(new java.awt.Color(255, 51, 51));
                jLabel18.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel18.setForeground(new java.awt.Color(75, 156, 211));
                jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel18.setText("Book ID     :");
                book_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                jLabel19.setBackground(new java.awt.Color(75, 156, 211));
                jLabel19.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                jLabel19.setForeground(new java.awt.Color(75, 156, 211));
                jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel19.setText("Student ID :");
                student_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                returnBook.setBackground(new java.awt.Color(75, 156, 211));
                returnBook.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                returnBook.setForeground(new java.awt.Color(242, 242, 242));
                returnBook.setText("RETURN");
                returnBook.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnBookActionPerformed(evt);
                        }
                });
                findBook.setBackground(new java.awt.Color(75, 156, 211));
                findBook.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
                findBook.setForeground(new java.awt.Color(242, 242, 242));
                findBook.setText("FIND DATA");
                findBook.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                findBookActionPerformed(evt);
                        }
                });
                jPanel10.setBackground(new java.awt.Color(75, 156, 211));
                jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jPanel10MouseClicked(evt);
                        }
                });
                jLabel25.setBackground(new java.awt.Color(0, 51, 0));
                jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-close-30.png"))); // NOI18N
                javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                jPanel10.setLayout(jPanel10Layout);
                jPanel10Layout.setHorizontalGroup(
                                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel10Layout.createSequentialGroup()
                                                                                .addContainerGap(14, Short.MAX_VALUE)
                                                                                .addComponent(jLabel25)
                                                                                .addGap(12, 12, 12)));
                jPanel10Layout.setVerticalGroup(
                                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel10Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel25,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                42, Short.MAX_VALUE)
                                                                .addContainerGap()));
                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout
                                                                .createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jPanel10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel5Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                false)
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                jPanel5Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(116, 116,
                                                                                                                                                116)
                                                                                                                                .addComponent(jLabel17)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(jLabel16))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                jPanel5Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(105, 105,
                                                                                                                                                105)
                                                                                                                                .addGroup(jPanel5Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addGroup(jPanel5Layout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel18)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(book_id,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                154,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addGroup(jPanel5Layout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel19)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addComponent(student_id)))))
                                                                                .addGroup(jPanel5Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(105, 105, 105)
                                                                                                .addGroup(jPanel5Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(returnBook,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                263,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(findBook,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                263,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addContainerGap(83, Short.MAX_VALUE)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(jPanel10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(topGap, topGap, topGap)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel16)
                                                                                .addComponent(jLabel17))
                                                                .addGap(48, 48, 48)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(book_id,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                36,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel18))
                                                                .addGap(55, 55, 55)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel19)
                                                                                .addComponent(student_id,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                38,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(62, 62, 62)
                                                                .addComponent(findBook,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(33, 33, 33)
                                                                .addComponent(returnBook,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                panel1width,
                                                                                panel1width,
                                                                                panel1width)
                                                                .addComponent(jPanel3,
                                                                                panel2width, panel2width,
                                                                                panel2width)
                                                                .addComponent(jPanel5,
                                                                                panel3width, panel3width,
                                                                                panel3width)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        }// GEN-LAST:event_jButton5ActionPerformed

        private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton5MouseClicked
                this.dispose();
                new Dashboard().setVisible(true);
        }// GEN-LAST:event_jButton5MouseClicked

        private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel10MouseClicked
                this.dispose();
        }// GEN-LAST:event_jPanel10MouseClicked

        private void findBookActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findBookActionPerformed
                try {
                        con = DriverManager.getConnection(url, user, pass);
                        pst = con.prepareStatement("SELECT * FROM books WHERE book_id = ?");
                        pst.setString(1, book_id.getText());
                        rt = pst.executeQuery();
                        if (!rt.next()) {
                                JOptionPane.showMessageDialog(null, "Book is not available.");
                        } else {
                                book_id_var = rt.getInt("book_id");
                                bookId.setText(String.valueOf(rt.getInt("book_id")));
                                bookTitle.setText(rt.getString("title"));
                                bookAuthor.setText(rt.getString("author"));
                                bookISBN.setText(rt.getString("isbn"));
                                bookLanguage.setText(rt.getString("language"));
                                bookPublisher.setText(rt.getString("publisher"));
                        }
                        // Ensure consistent alignment
                        bookId.setHorizontalAlignment(SwingConstants.LEFT);
                        bookTitle.setHorizontalAlignment(SwingConstants.LEFT);
                        bookAuthor.setHorizontalAlignment(SwingConstants.LEFT);
                        bookISBN.setHorizontalAlignment(SwingConstants.LEFT);
                        bookLanguage.setHorizontalAlignment(SwingConstants.LEFT);
                        bookPublisher.setHorizontalAlignment(SwingConstants.LEFT);
                        pst = con.prepareStatement("SELECT * FROM students WHERE student_id = ?");
                        pst.setString(1, student_id.getText());
                        rt = pst.executeQuery();
                        if (!rt.next()) {
                                JOptionPane.showMessageDialog(null, "Student is not available.");
                        } else {
                                student_id_var = rt.getInt("student_id");
                                studentId.setText(String.valueOf(rt.getInt("student_id")));
                                studentName.setText(rt.getString("name"));
                                studentPhone.setText(rt.getString("phone"));
                                studentCourse.setText(rt.getString("course"));
                                studentAddress.setText(rt.getString("address"));
                        }
                } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Some error occured.");
                }
        }// GEN-LAST:event_findBookActionPerformed

        private void returnBookActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_returnBookActionPerformed
                if (book_id_var == 0 || student_id_var == 0) {
                        JOptionPane.showMessageDialog(null, "Choose student and book before issuing book to student.");
                } else {
                        try {
                                con = DriverManager.getConnection(url, user, pass);
                                pst = con.prepareStatement(
                                                "SELECT status FROM issue_books WHERE book_id=? AND student_id=?");
                                pst.setInt(1, book_id_var);
                                pst.setInt(2, student_id_var);
                                rt = pst.executeQuery();
                                if (!rt.next()) {
                                        JOptionPane.showMessageDialog(null, "Book has not been issued.");
                                        clearData();
                                }
                                if (rt.getString("status").equals("returned")) {
                                        JOptionPane.showMessageDialog(null, "Book has already been returned.");
                                        clearData();
                                } else {
                                        pst = con.prepareStatement(
                                                        "UPDATE issue_books SET status='returned' WHERE book_id=? AND student_id=?");
                                        pst.setString(1, book_id.getText());
                                        pst.setString(2, student_id.getText());
                                        pst.executeUpdate();
                                        pst.close();
                                        pst = con.prepareStatement("UPDATE books SET isbn=isbn + 1 WHERE book_id=?");
                                        pst.setString(1, book_id.getText());
                                        pst.executeUpdate();
                                        pst.close();
                                        JOptionPane.showMessageDialog(null, "Book has been returned.");
                                        clearData();
                                }
                        } catch (SQLException e) {
                                JOptionPane.showMessageDialog(null, "Some error occured.");
                        }
                }
        }// GEN-LAST:event_returnBookActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new ReturnBook().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel bookAuthor;
        private javax.swing.JLabel bookId;
        private javax.swing.JLabel bookLanguage;
        private javax.swing.JLabel bookPublisher;
        private javax.swing.JLabel bookISBN;
        private javax.swing.JLabel bookTitle;
        private javax.swing.JTextField book_id;
        private javax.swing.JButton findBook;
        private javax.swing.JButton jButton5;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel25;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel10;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JButton returnBook;
        private javax.swing.JLabel studentAddress;
        private javax.swing.JLabel studentCourse;
        private javax.swing.JLabel studentId;
        private javax.swing.JLabel studentName;
        private javax.swing.JLabel studentPhone;
        private javax.swing.JTextField student_id;
        // End of variables declaration//GEN-END:variables
}
