/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.awt.Dimension;
import java.awt.Toolkit;

public class LoginPage extends javax.swing.JFrame {
        String url = "jdbc:mysql://localhost:3306/lms_db";
        String user = "root";
        String pass = "VRINDA";
        // Connection con = DriverManager.getConnection(url, username, password);
        Connection con;
        PreparedStatement pst;
        ResultSet rt;
        public static String sqlUserType;

        /**
         * Creates new form LoginPage
         */
        public LoginPage() {
                setUndecorated(true);
                initComponents();
                setExtendedState(LoginPage.MAXIMIZED_BOTH);
                setResizable(true);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                username = new javax.swing.JTextField();
                password = new javax.swing.JPasswordField();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                usertype = new javax.swing.JComboBox<>();
                jLabel6 = new javax.swing.JLabel();
                login = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                showPassword = new javax.swing.JCheckBox();
                jPanel3 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);
                setResizable(false);
                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jPanel2.setBackground(new java.awt.Color(75, 156, 211));
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("USERNAME");
                username.setOpaque(true);
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("PASSWORD");
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/username.png"))); // NOI18N
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password.png"))); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("USER TYPE");
                usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
                                "ADMIN",
                                "LIBRARIAN"
                }));
                usertype.setBorder(null);
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usertype.png"))); // NOI18N
                login.setBackground(new java.awt.Color(75, 156, 211));
                login.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
                login.setForeground(new java.awt.Color(255, 255, 255));
                login.setText("LOGIN");
                login.setBorder(null);
                login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                login.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginActionPerformed(evt);
                        }
                });
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-close-30.png"))); // NOI18N
                jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel7MouseClicked(evt);
                        }
                });
                showPassword.setBackground(new java.awt.Color(75, 156, 211));
                showPassword.setForeground(new java.awt.Color(255, 255, 255));
                showPassword.setText("Show Password");
                showPassword.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                showPasswordActionPerformed(evt);
                        }
                });
                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                int height = (int) (Toolkit.getDefaultToolkit().getScreenSize().height);
                int width = (int) (Toolkit.getDefaultToolkit().getScreenSize().width);
                int heightAdjusted = (int) (height * 0.3);
                double ratio = (double) (0.4);
                int widthAdjust1 = (int) (width * (1 - ratio));
                int widthAdjust2 = (int) (width * ratio);
                int widthAdjust3 = (int) (widthAdjust2 * (ratio - 0.1));
                int widthAdjust4 = (int) (widthAdjust2 * (ratio + 0.05));
                jPanel2.setLayout(jPanel2Layout);
                jPanel2.setBackground(new java.awt.Color(75, 156, 211));
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(widthAdjust4,
                                                                                                                                                widthAdjust4,
                                                                                                                                                widthAdjust4)
                                                                                                                                .addComponent(login,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                130,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(widthAdjust3,
                                                                                                                                                widthAdjust3,
                                                                                                                                                widthAdjust3)
                                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addComponent(jLabel6))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                .addComponent(jLabel1)
                                                                                                                                                .addComponent(username)
                                                                                                                                                .addComponent(password)
                                                                                                                                                .addComponent(jLabel2,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                90,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(usertype,
                                                                                                                                                                0,
                                                                                                                                                                255,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(showPassword,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                114,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                .addGap(0, 135, Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel2Layout.createSequentialGroup()
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel7)))
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addGap(heightAdjusted, heightAdjusted, heightAdjusted)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(username,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                34,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jLabel3))
                                                                .addGap(50, 50, 50)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel2)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(password,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                34,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jLabel4))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(showPassword)
                                                                .addGap(50, 50, 50)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel5)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(usertype,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                33,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jLabel6))
                                                                .addGap(50, 50, 50)
                                                                .addComponent(login,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                49,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(168, Short.MAX_VALUE)));
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/66072.png"))); // NOI18N
                jLabel8.setSize(widthAdjust1, height);
                int labelSize = (int) (widthAdjust1 * (ratio / 2));
                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3.setBackground(new java.awt.Color(255, 255, 255));
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap(labelSize, labelSize)
                                                                .addComponent(jLabel8)
                                                                .addContainerGap()));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel8,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                0, Short.MAX_VALUE)));
                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addComponent(jPanel3,
                                                                                widthAdjust1,
                                                                                widthAdjust1,
                                                                                widthAdjust1)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jPanel2,
                                                                                widthAdjust2,
                                                                                widthAdjust2,
                                                                                widthAdjust2)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel2,
                                                                                                height,
                                                                                                height,
                                                                                                height)
                                                                                .addComponent(jPanel3,
                                                                                                height,
                                                                                                height,
                                                                                                height))));
                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                Short.MAX_VALUE));
                pack();
                setLocationRelativeTo(null);
        } // </editor-fold>//GEN-END:initComponents

        private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_showPasswordActionPerformed
                if (showPassword.isSelected()) {
                        password.setEchoChar((char) 0);
                } else {
                        password.setEchoChar('*');
                }
        } // GEN-LAST:event_showPasswordActionPerformed

        public static String getSecurePassword(String password) {
                String generatedPassword = null;
                try {
                        MessageDigest md = MessageDigest.getInstance("SHA-256");
                        byte[] bytes = md.digest(password.getBytes());
                        StringBuilder sb = new StringBuilder();
                        for (byte b : bytes) {
                                sb.append(String.format("%02x", b));
                        }
                        generatedPassword = sb.toString();
                } catch (NoSuchAlgorithmException e) {
                        e.printStackTrace();
                }
                return generatedPassword;
        }

        private void loginActionPerformed(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_loginActionPerformed
                String passwordString = new String(password.getPassword());
                if (username.getText().equals("") || passwordString.equals("")) {
                        JOptionPane.showMessageDialog(null, "Enter the details to log in.");
                } else {
                        String hashedPassword = getSecurePassword(passwordString);
                        try {
                                con = DriverManager.getConnection(url, user, pass);
                                if (usertype.getSelectedItem().toString().equals("ADMIN")) {
                                        pst = con.prepareStatement(
                                                        "SELECT * FROM admin WHERE username = ? AND password = ?");
                                        sqlUserType = "admin";
                                } else {
                                        pst = con.prepareStatement(
                                                        "SELECT * FROM librarians WHERE username = ? AND password = ?");
                                        sqlUserType = "librarian";
                                }
                                pst.setString(1, username.getText());
                                pst.setString(2, hashedPassword);
                                rt = pst.executeQuery();
                                if (rt.next()) {
                                        JOptionPane.showMessageDialog(null, "Login Successful");
                                        this.dispose();
                                        new Dashboard().setVisible(true);
                                } else {
                                        JOptionPane.showMessageDialog(null,
                                                        "Some error occured. Please try again with correct credentials.");
                                }
                        } catch (SQLException e) {
                                JOptionPane.showMessageDialog(null, e.getMessage());
                        }
                }
        } // GEN-LAST:event_loginActionPerformed

        private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) { // GEN-FIRST:event_jLabel7MouseClicked
                this.dispose();
        } // GEN-LAST:event_jLabel7MouseClicked

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                                | javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(LoginPage.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new LoginPage().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JButton login;
        private javax.swing.JPasswordField password;
        private javax.swing.JCheckBox showPassword;
        private javax.swing.JTextField username;
        private javax.swing.JComboBox<String> usertype;
        // End of variables declaration//GEN-END:variables
}