/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.Toolkit;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageLibrarian extends javax.swing.JFrame {
    String url = "jdbc:mysql://localhost:3306/lms_db";
    String user = "root";
    String pass = "VRINDA";
    // Connection con = DriverManager.getConnection(url, username, password);
    Connection con;
    PreparedStatement pst;
    ResultSet rt;
    int id, selectedRow = 0;

    public void clearData() {
        name.setText("");
        phone.setText("");
        username.setText("");
        password.setText("");
        address.setText("");
        if (id > 0) {
            id = 0;
            editLib.setEnabled(false);
            deleteLib.setEnabled(false);
            addLib.setEnabled(true);
        }
    }

    public void showLib() {
        try {
            con = DriverManager.getConnection(url, user, pass);
            pst = con.prepareStatement("SELECT * FROM librarians");
            rt = pst.executeQuery();
            DefaultTableModel tabModel = (DefaultTableModel) (lib_table.getModel());
            tabModel.setRowCount(0);
            while (rt.next()) {
                Vector libRow = new Vector();
                libRow.add(rt.getInt("lib_id"));
                libRow.add(rt.getString("name"));
                libRow.add(rt.getString("username"));
                libRow.add(rt.getString("phone"));
                libRow.add(rt.getString("address"));
                tabModel.addRow(libRow);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Some error occured.");
        }
    }

    /**
     * Creates new form ManageLibrarian
     */
    public ManageLibrarian() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Maximize the frame
        showLib();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        addLib = new javax.swing.JButton();
        editLib = new javax.swing.JButton();
        deleteLib = new javax.swing.JButton();
        clearLib = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lib_table = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        jPanel1.setBackground(new java.awt.Color(75, 156, 211));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Name");
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone");
        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);
        addLib.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        addLib.setText("ADD NEW LIBRARIAN");
        addLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLibActionPerformed(evt);
            }
        });
        editLib.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        editLib.setText("EDIT EXISTING LIBRARIAN");
        editLib.setEnabled(false);
        editLib.setMaximumSize(new java.awt.Dimension(191, 28));
        editLib.setMinimumSize(new java.awt.Dimension(191, 28));
        editLib.setPreferredSize(new java.awt.Dimension(191, 28));
        editLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editLibMouseClicked(evt);
            }
        });
        deleteLib.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        deleteLib.setText("DELETE LIBRARIAN");
        deleteLib.setEnabled(false);
        deleteLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLibMouseClicked(evt);
            }
        });
        clearLib.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        clearLib.setText("CLEAR FORM");
        clearLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearLibMouseClicked(evt);
            }
        });
        jButton5.setBackground(new java.awt.Color(75, 156, 211));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addNewBooksIcons/icons8_Rewind_48px.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");
        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD LIBRARIAN");
        int width = (int) (Toolkit.getDefaultToolkit().getScreenSize().width);
        int height = (int) (Toolkit.getDefaultToolkit().getScreenSize().height);
        int panel1gap = (int) (width * 0.075);
        int topGap = (int) (height * 0.1);
        int textBoxSize = 250;
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(panel1gap, panel1gap)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(name, textBoxSize, textBoxSize, textBoxSize)
                                                        .addComponent(jLabel1)
                                                        .addComponent(phone, textBoxSize, textBoxSize, textBoxSize))
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(jLabel8)
                                                                        .addComponent(password, textBoxSize,
                                                                                textBoxSize, textBoxSize)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(username, textBoxSize, textBoxSize,
                                                                        textBoxSize))))
                                        .addComponent(jScrollPane1, textBoxSize * 2 + 20, textBoxSize * 2 + 20,
                                                textBoxSize * 2 + 20)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton5)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap(panel1gap, panel1gap)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addLib, textBoxSize, textBoxSize, textBoxSize)
                                                        .addComponent(deleteLib, textBoxSize, textBoxSize, textBoxSize))
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(editLib, textBoxSize, textBoxSize, textBoxSize)
                                                        .addComponent(clearLib, textBoxSize, textBoxSize,
                                                                textBoxSize))))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(topGap, topGap, topGap)
                                .addComponent(jLabel9)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addLib, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editLib, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(clearLib, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteLib, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(108, Short.MAX_VALUE)));
        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 156, 211));
        jLabel5.setText("Manage Librarians");
        jLabel6.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/icons/library.png"))); // NOI18N
        lib_table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "ID", "Name", "Username", "Phone", "Address"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        lib_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lib_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lib_table);
        lib_table.setForeground(new java.awt.Color(0, 0, 0));
        lib_table.setShowVerticalLines(true);
        lib_table.setShowHorizontalLines(true);
        lib_table.setBorder(new javax.swing.border.EtchedBorder());
        int widthMin = (int) (width * 0.03);
        int widthMid = (int) (width * 0.04);
        int widthMidMax = (int) (width * 0.06);
        int widthStr = (int) (width * 0.12);
        int table = 0;
        if (lib_table.getColumnModel().getColumnCount() > 0) {
            lib_table.getColumnModel().getColumn(0).setMinWidth(widthMin);
            lib_table.getColumnModel().getColumn(0).setPreferredWidth(widthMin);
            lib_table.getColumnModel().getColumn(0).setMaxWidth(widthMin);
            table += widthMin;
            lib_table.getColumnModel().getColumn(1).setMinWidth(widthStr);
            lib_table.getColumnModel().getColumn(1).setPreferredWidth(widthStr);
            lib_table.getColumnModel().getColumn(1).setMaxWidth(widthStr);
            table += widthStr;
            lib_table.getColumnModel().getColumn(2).setMinWidth(widthMid);
            lib_table.getColumnModel().getColumn(2).setPreferredWidth(widthMid);
            lib_table.getColumnModel().getColumn(2).setMaxWidth(widthMid);
            table += widthMid;
            lib_table.getColumnModel().getColumn(3).setMinWidth(widthMidMax);
            lib_table.getColumnModel().getColumn(3).setPreferredWidth(widthMidMax);
            lib_table.getColumnModel().getColumn(3).setMaxWidth(widthMidMax);
            table += widthMidMax;
            lib_table.getColumnModel().getColumn(4).setMinWidth(widthStr);
            lib_table.getColumnModel().getColumn(4).setPreferredWidth(widthStr);
            lib_table.getColumnModel().getColumn(4).setMaxWidth(widthStr);
            table += widthStr;
        }
        lib_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jPanel10.setBackground(new java.awt.Color(75, 156, 211));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-close-30.png"))); // NOI18N
        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addContainerGap(14, Short.MAX_VALUE)
                                .addComponent(jLabel25)
                                .addGap(12, 12, 12)));
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addContainerGap()));
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(jScrollPane2, table, table, table)))
                                .addContainerGap(131, Short.MAX_VALUE)));
        int jlabel5Gap = (int) (topGap + topGap * 0.5);
        int jTableGap = (int) (height * 0.05);
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(topGap, topGap, topGap)
                                                .addComponent(jLabel6))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(jlabel5Gap, jlabel5Gap, jlabel5Gap)
                                                .addComponent(jLabel5))
                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(jTableGap, jTableGap, jTableGap)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        int layoutAdjust1 = (int) (width * 0.4);
        int layoutAdjust2 = (int) (width * 0.6);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, layoutAdjust1, layoutAdjust1, layoutAdjust1)
                                .addComponent(jPanel2, layoutAdjust2, layoutAdjust2, layoutAdjust2)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static String getSecurePassword(String password) {
        String generatedPassword = null;
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] bytes = md.digest(password.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : bytes) {
                sb.append(String.format("%02x", b));
            }
            generatedPassword = sb.toString();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        return generatedPassword;
    }

    private void addLibActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addLibActionPerformed
        if (name.getText().isEmpty() || phone.getText().isEmpty() || username.getText().isEmpty()
                || password.getText().isEmpty() || address.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fill all the data before submission.");
        } else {
            String hashedPassword = getSecurePassword(password.getText());
            try {
                con = DriverManager.getConnection(url, user, pass);
                pst = con.prepareStatement(
                        "INSERT INTO librarians (name,username, password, phone, address) VALUES (?,?,?,?,?)");
                pst.setString(1, name.getText());
                pst.setString(2, username.getText());
                pst.setString(3, hashedPassword);
                pst.setString(4, phone.getText());
                pst.setString(5, address.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Librarian has been successfully added.");
                showLib();
                clearData();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }// GEN-LAST:event_addLibActionPerformed

    private void editLibMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_editLibMouseClicked
        if (id != 0) {
            if (name.getText().isEmpty() || username.getText().isEmpty() || phone.getText().isEmpty()
                    || address.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Fill all the data before submission.");
            } else {
                try {
                    con = DriverManager.getConnection(url, user, pass);
                    if (password.getText().isEmpty()) {
                        pst = con.prepareStatement(
                                "UPDATE librarians SET name=?,username=?,phone=?,address=? WHERE lib_id=?");
                        pst.setString(1, name.getText());
                        pst.setString(2, username.getText());
                        pst.setString(3, phone.getText());
                        pst.setString(4, address.getText());
                        pst.setInt(5, id);
                    } else {
                        pst = con.prepareStatement(
                                "UPDATE librarians SET name=?,username=?,password=?,phone=?,address=? WHERE lib_id=?");
                        pst.setString(1, name.getText());
                        pst.setString(2, username.getText());
                        pst.setString(3, password.getText());
                        pst.setString(4, phone.getText());
                        pst.setString(5, address.getText());
                        pst.setInt(6, id);
                    }
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Librarian's details has been successfully updated.");
                    showLib();
                    clearData();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Some error occured. Please try again.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a row to edit.");
        }
    }// GEN-LAST:event_editLibMouseClicked

    private void deleteLibMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_deleteLibMouseClicked
        if (id != 0) {
            try {
                con = DriverManager.getConnection(url, user, pass);
                pst = con.prepareStatement("DELETE FROM librarians WHERE lib_id=?");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Librarian has been successfully deleted.");
                showLib();
                clearData();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Some error occured. Please try again.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a row to delete.");
        }
    }// GEN-LAST:event_deleteLibMouseClicked

    private void clearLibMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_clearLibMouseClicked
        clearData();
    }// GEN-LAST:event_clearLibMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton5MouseClicked
        this.dispose();
        new Dashboard().setVisible(true);
    }// GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
    }// GEN-LAST:event_jButton5ActionPerformed

    private void lib_tableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lib_tableMouseClicked
        selectedRow = lib_table.getSelectedRow();
        if (lib_table.getSelectedRowCount() > 0) {
            addLib.setEnabled(false);
            deleteLib.setEnabled(true);
            editLib.setEnabled(true);
            id = (int) lib_table.getValueAt(selectedRow, 0);
            String sqlusername, sqlpassword;
            try {
                con = DriverManager.getConnection(url, user, pass);
                pst = con.prepareStatement("SELECT username,password FROM librarians WHERE lib_id=?");
                pst.setInt(1, id);
                rt = pst.executeQuery();
                rt.next();
                sqlusername = rt.getString("username");
                sqlpassword = rt.getString("password");
                username.setText(sqlusername);
                password.setText(sqlpassword);
                name.setText(lib_table.getValueAt(selectedRow, 1).toString());
                phone.setText(lib_table.getValueAt(selectedRow, 3).toString());
                address.setText(lib_table.getValueAt(selectedRow, 4).toString());
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            clearData();
        }
    }// GEN-LAST:event_lib_tableMouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel10MouseClicked
        this.dispose();
    }// GEN-LAST:event_jPanel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageLibrarian.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageLibrarian.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageLibrarian.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageLibrarian.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageLibrarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLib;
    private javax.swing.JTextArea address;
    private javax.swing.JButton clearLib;
    private javax.swing.JButton deleteLib;
    private javax.swing.JButton editLib;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lib_table;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
